version: "3.2"
name: demo
services:
  demo:
    image: oidc-passkey/demo
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
      network: host
    environment:
    - APACHE_EMAIL
    - APACHE_HOSTNAME
    - APACHE_LOG_LEVEL
    - KEYCLOAK_HOSTNAME
    volumes:
    - state:/mnt/state
    network_mode: host
  demo-1:
    image: oidc-passkey/demo-1
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
      network: host
    environment:
    - APACHE_EMAIL
    - APACHE_HOSTNAME
    - APACHE_LOG_LEVEL
    - KEYCLOAK_HOSTNAME
    - KEYCLOAK_OIDC_REMOTE_USER_CLAIM
    - KEYCLOAK_OIDC_SCOPE
    - OIDC_PASSKEY_DEMO=1
    volumes:
    - state:/mnt/state
    network_mode: host
  demo-2:
    image: oidc-passkey/demo-2
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
      network: host
    environment:
    - APACHE_EMAIL
    - APACHE_HOSTNAME
    - APACHE_LOG_LEVEL
    - KEYCLOAK_HOSTNAME
    - KEYCLOAK_OIDC_REMOTE_USER_CLAIM
    - KEYCLOAK_OIDC_SCOPE
    - OIDC_PASSKEY_DEMO=2
    volumes:
    - state:/mnt/state
    network_mode: host
  demo-3:
    image: oidc-passkey/demo-3
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
      network: host
    environment:
    - APACHE_EMAIL
    - APACHE_HOSTNAME
    - APACHE_LOG_LEVEL
    - KEYCLOAK_HOSTNAME
    - OIDC_PASSKEY_DEMO=3
    volumes:
    - state:/mnt/state
    network_mode: host
  demo-4:
    image: oidc-passkey/demo-4
    init: true
    build:
      context: .
      dockerfile: Dockerfile.demo
      network: host
    environment:
    - APACHE_EMAIL
    - APACHE_HOSTNAME
    - APACHE_LOG_LEVEL
    - KEYCLOAK_HOSTNAME
    - OIDC_PASSKEY_DEMO=4
    volumes:
    - state:/mnt/state
    network_mode: host
volumes:
  state:
    external: true
