FROM docker.io/neilpang/acme.sh

COPY files/state /usr/local/bin/

VOLUME /acme.sh
VOLUME /mnt/state
VOLUME /var/run/docker.sock

ENV ACME_EAB_HMAC_KEY ""
ENV ACME_EAB_KID ""
ENV ACME_EMAIL ""
ENV ACME_SERVER ""
ENV APACHE_HOSTNAME ""
ENV KEYCLOAK_HOSTNAME ""

COPY files/issue_19321 /usr/local/bin/

VOLUME /mnt/acme-hook

COPY files/acme/entrypoint /
ENTRYPOINT ["/entrypoint"]
