version: "3.2"
name: base
services:
  acme:
    image: oidc-passkey/acme
    build:
      context: .
      dockerfile: Dockerfile.acme
      network: host
    environment:
    - ACME_EMAIL
    - APACHE_HOSTNAME
    - KEYCLOAK_HOSTNAME
    volumes:
    - acme:/acme.sh
    - state:/mnt/state
    - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    command: "daemon"
  db:
    image: oidc-passkey/db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
    - POSTGRES_KEYCLOAK_PASSWORD
    - POSTGRES_PASSWORD
    volumes:
    - state:/mnt/state
    - data:/var/lib/postgresql/data
    network_mode: host
  keycloak:
    image: oidc-passkey/keycloak
    init: true
    build:
      context: .
      dockerfile: Dockerfile.keycloak
      network: host
    environment:
    - APACHE_HOSTNAME
    - KEYCLOAK_ADMIN_PASSWORD
    - KEYCLOAK_HOSTNAME
    - KEYCLOAK_LOG_LEVEL
    - LDAP_URL
    - POSTGRES_KEYCLOAK_PASSWORD
    volumes:
    - state:/mnt/state
    - ./blob.jwt:/mnt/blob.jwt:ro
    network_mode: host
volumes:
  acme:
    external: true
  data:
    external: true
  state:
    external: true
