#!/bin/ash

echo "KEYCLOAK_REALM=$KEYCLOAK_REALM"
echo "LDAP_PORT=$LDAP_PORT"

[ -n "$KEYCLOAK_REALM" ]
[ -n "$LDAP_PORT" ]

. /usr/local/bin/issue_19321
fqdn=$(fqdn_19321)

# wait for Keycloak to be ready

. /usr/local/bin/state

wait_state KEYCLOAK_READY /mnt/state/state.keycloak

# start GLAuth and its Keycloak plugin

/opt/glauth/bin/glauth \
  --ldaps $fqdn:$LDAP_PORT \
  --ldaps-cert /mnt/state/$KEYCLOAK_HOSTNAME.cer \
  --ldaps-key /mnt/state/$KEYCLOAK_HOSTNAME.key \
  --config /opt/glauth/etc/glauth.cfg
