#!/bin/bash
set -e
trap 'echo "error: $0:$LINENO"' ERR

[ $# -eq 2 ]

key=$1
app_id=$2 # $1 is either app_id or realm_id, depending on key
realm_id=$2

. /usr/local/bin/issue_19321
fqdn=$(fqdn_19321)
[ -n "$fqdn" ]

case $key in
client_id)
  case $app_id in
  1|2|3|4|6)
    echo demo-$app_id-client
    ;;
  *)
    exit 1
  esac
  ;;
display_name)
  case $app_id in
  1|2|3|4|6)
    echo "demo #$app_id"
    ;;
  *)
    exit 1
  esac
  ;;
flow)
  case $app_id in
  1|3)
    echo kundk-1fa
    ;;
  2|4|6)
    echo kundk-2fa
    ;;
  *)
    exit 1
  esac
  ;;
ldap_attribute_first_name)
  case $app_id in
  1|2|3|4|6)
    echo ""
    ;;
  *)
    exit 1
  esac
  ;;
ldap_auth_type)
  case $app_id in
  1|2|3|4|6)
    echo simple
    ;;
  *)
    exit 1
  esac
  ;;
ldap_bind_credential)
  case $app_id in
  1|2|3|4|6)
    echo password
    ;;
  *)
    exit 1
  esac
  ;;
ldap_bind_dn)
  case $app_id in
  1|2|3|4|6)
    echo "cn=read-only-admin,dc=example,dc=com"
    ;;
  *)
    exit 1
  esac
  ;;
ldap_connection_url)
  case $app_id in
  1|2|3|4|6)
    echo ldap://ldap.forumsys.com
    ;;
  *)
    exit 1
  esac
  ;;
ldap_rdn_ldap_attribute)
  case $app_id in
  1|2|3|4|6)
    echo uid
    ;;
  *)
    exit 1
  esac
  ;;
ldap_username_ldap_attribute)
  case $app_id in
  1|2|3|4|6)
    echo uid
    ;;
  *)
    exit 1
  esac
  ;;
ldap_users_dn)
  case $app_id in
  1|2|3|4|6)
    echo "dc=example,dc=com"
    ;;
  *)
    exit 1
  esac
  ;;
ldap_user_object_class)
  case $app_id in
  1|2|3|4|6)
    echo inetOrgPerson
    ;;
  *)
    exit 1
  esac
  ;;
ldap_uuid_ldap_attribute)
  case $app_id in
  1|2|3|4|6)
    echo entryUUID
    ;;
  *)
    exit 1
  esac
  ;;
post_logout_redirect_uri)
  case $app_id in
  1|2|3|4|6)
    echo https://$fqdn
    ;;
  *)
    exit 1
  esac
  ;;
protocol)
  case $app_id in
  1|2|6)
    echo oidc
    ;;
  3|4)
    echo saml
    ;;
  *)
    exit 1
  esac
  ;;
realm)
  case $app_id in
  1|2|3|4|6)
    echo kundk-demo-$realm_id
    ;;
  *)
    exit 1
  esac
  ;;
redirect_uri)
  case $app_id in
  1|2)
    echo "https://$fqdn:$((9443 + $app_id))/vanity.html"
    ;;
  3|4)
    echo "https://$fqdn:$((9443 + $app_id))/*"
    ;;
  6)
    echo $VSPHERE_SERVER/ui/login/oauth2/authcode
    ;;
  *)
    exit 1
  esac
  ;;
saml_assertion_consumer_url_redirect)
  case $app_id in
  3|4)
    echo "https://$fqdn:$((9443 + $app_id))"
    ;;
  *)
    exit 1
  esac
  ;;
saml_single_logout_service_url_redirect)
  case $app_id in
  3|4)
    echo "https://$fqdn:$((9443 + $app_id))/Shibboleth.sso/SLO/Redirect"
    ;;
  *)
    exit 1
  esac
  ;;
vsphere_domain)
  case $app_id in
  1|2|3|4)
    echo ""
    ;;
  6)
    echo $VSPHERE_DOMAIN
    ;;
  *)
    exit 1
  esac
  ;;
esac
