#!/bin/bash
set -e
trap 'echo "error: $0:$LINENO"' ERR

[ -n "$KEYCLOAK_ADMIN_PASSWORD" ]
[ -n "$KEYCLOAK_PORT" ] || KEYCLOAK_PORT=8444

. /usr/local/bin/issue_19321
fqdn=$(fqdn_19321)
[ -n "$fqdn" ]

config=/var/run/keycloak/kcadm.config
/opt/keycloak/bin/kcadm.sh config credentials \
  --config $config \
  --server https://$fqdn:$KEYCLOAK_PORT \
  --realm master \
  --user admin \
  --password $KEYCLOAK_ADMIN_PASSWORD
