#!/bin/bash
set -e
trap 'echo "error: $0:$LINENO"' ERR

test $# -eq 3
realm=$1
user_id=$2
credential_id=$3

config=/var/run/keycloak/kcadm.config
test -f $config # i.e. past kc_login

/opt/keycloak/bin/kcadm.sh delete --config $config -r $realm \
  users/$user_id/credentials/$credential_id
