#!/bin/bash
set -e
trap 'echo "error: $0:$LINENO"' ERR

podman secret rm keycloak-admin-password &> /dev/null || true
podman secret rm postgres-keycloak-password &> /dev/null || true
podman secret rm postgres-password &> /dev/null || true
podman secret rm postgres-password &> /dev/null || true

encode() {
  [ $# -eq 1 ]
  echo -n $1 | base64 -w 0
}

for secret in keycloak-admin-password keycloak-db-password; do
  echo "$secret:"
  read password
  echo '{"password":"'$(encode $password)'"}' | \
    podman secret create --driver file $secret - > /dev/null
done

secret=acme-eab
echo "$secret (kid):"
read kid
echo "$secret (hmac_key):"
read hmac_key
echo '{"kid":"'$(encode $kid)'","hmac_key":"'$(encode $hmac_key)'"}' | \
  podman secret create --driver file $secret - > /dev/null
