#!/bin/bash
set -e
trap 'echo "error: $0:$LINENO"' ERR

for secret in keycloak-admin-password postgres-keycloak-password postgres-password acme-eab; do
  podman secret rm --all &> /dev/null || true
done

encode() {
  [ $# -eq 1 ]
  echo -n $1 | base64 -w 0
}

echo keycloak-admin-password:
read password
echo '{"password":"'$(encode $password)'"}' | \
  podman secret create --driver file keycloak-admin-password - > /dev/null

echo postgres-keycloak-password:
read password
echo '{"password":"'$(encode $password)'"}' | \
  podman secret create --driver file postgres-keycloak-password - > /dev/null

echo postgres-password:
read password
echo '{"password":"'$(encode $password)'"}' | \
  podman secret create --driver file postgres-password - > /dev/null

echo "acme_eab (kid)"
read kid
echo "acme_eab (hmac_key)"
read hmac_key
echo '{"kid":"'$(encode $kid)'","hmac_key":"'$(encode $hmac_key)'"}' | \
  podman secret create --driver file acme-eab - > /dev/null
