apiVersion: v1
kind: ConfigMap
metadata:
  name: config-base
data:
  ACME_EMAIL:
  ACME_SERVER:
  APACHE_HOSTNAME:
  APP_IDS:
  KEYCLOAK_EMAIL:
  KEYCLOAK_HOSTNAME:
  KEYCLOAK_LOG_LEVEL:
  LDAP_URL:
  REALM_IDS:
  SMTP_SERVER:
