#!/usr/bin/env sh
set -e

echo "ACME_EAB_HMAC_KEY=$(echo $ACME_EAB_HMAC_KEY | sed s/./\*/g)"
echo "ACME_EAB_KID=$(echo $ACME_EAB_KID | sed s/./\*/g)"
echo "ACME_EMAIL=$ACME_EMAIL"
echo "ACME_SERVER=$ACME_SERVER"
echo "APACHE_HOSTNAME=$APACHE_HOSTNAME"
echo "KEYCLOAK_HOSTNAME=$KEYCLOAK_HOSTNAME"

. /usr/local/bin/issue_19321

[ -n "$ACME_EMAIL" ]
[ $([ -n $ACME_EAB_HMAC_KEY ]; echo $?) -eq $([ -n $ACME_EAB_KID ]; echo $?) ]
[ -n "$APACHE_HOSTNAME" ] || APACHE_HOSTNAME=$(fqdn_19321)
[ -n "$KEYCLOAK_HOSTNAME" ] || KEYCLOAK_HOSTNAME=$(fqdn_19321)

# handle acme.hook

if [ -s /mnt/acme.hook ]; then
  tar -C /acme.sh/ -xzf /mnt/acme.hook
fi

# update account with email address

debug=1

if [ -n "$ACME_SERVER" ]; then
  server="--server $ACME_SERVER"
else
  server=""
fi

if [ -n "$ACME_EAB_KID" ] && [ -n "$ACME_EAB_HMAC_KEY" ]; then
  eab="--eab-kid $ACME_EAB_KID --eab-hmac-key $ACME_EAB_HMAC_KEY"
else
  eab=""
fi

acme.sh --debug $debug $server $eab --register-account -m $ACME_EMAIL

# update state

. /usr/local/bin/state

set_state STARTED /mnt/state/state.acme

# issue or renew certificates

# check if acme.sh uses ECC certificates
grep ^DEFAULT_DOMAIN_KEY_LENGTH=ec /usr/local/bin/acme.sh

if [ ! -f /acme.sh/${APACHE_HOSTNAME}_ecc/$APACHE_HOSTNAME.cer ]; then
  acme.sh --debug $debug $server \
    --issue -d $APACHE_HOSTNAME --standalone --httpport 9080
else
  acme.sh --debug $debug $server \
     --renew -d $APACHE_HOSTNAME --standalone --httpport 9080 || true
fi

if [ $APACHE_HOSTNAME != $KEYCLOAK_HOSTNAME ]; then
  if [ ! -f /acme.sh/${KEYCLOAK_HOSTNAME}_ecc/$KEYCLOAK_HOSTNAME.cer ]; then
    acme.sh --debug $debug $server \
       --issue -d $KEYCLOAK_HOSTNAME --standalone --httpport 9080
  else
    acme.sh --debug $debug $server \
       --renew -d $KEYCLOAK_HOSTNAME --standalone --httpport 9080 || true
  fi
fi

# copy certificates, keys into shared volume

install -m 644 /acme.sh/${APACHE_HOSTNAME}_ecc/$APACHE_HOSTNAME.cer \
  /mnt/state/$APACHE_HOSTNAME.cer
install -m 644 /acme.sh/${APACHE_HOSTNAME}_ecc/$APACHE_HOSTNAME.key \
  /mnt/state/$APACHE_HOSTNAME.key
install -m 644 /acme.sh/${APACHE_HOSTNAME}_ecc/fullchain.cer \
  /mnt/state/${APACHE_HOSTNAME}_fullchain.cer

if [ $APACHE_HOSTNAME != $KEYCLOAK_HOSTNAME ]; then
  install -m 644 /acme.sh/${KEYCLOAK_HOSTNAME}_ecc/$KEYCLOAK_HOSTNAME.cer \
    /mnt/state/$KEYCLOAK_HOSTNAME.crt
  install -m 644 /acme.sh/${KEYCLOAK_HOSTNAME}_ecc/$KEYCLOAK_HOSTNAME.key \
    /mnt/state/$KEYCLOAK_HOSTNAME.key
  install -m 644 /acme.sh/${KEYCLOAK_HOSTNAME}_ecc/fullchain.cer \
    /mnt/state/${KEYCLOAK_HOSTNAME}_fullchain.cer
fi

# update state

set_state CERTIFICATES_READY /mnt/state/state.acme

# exec base image's entrypoint

exec /entry.sh "$@"
